import {Product} from "./product";

export const PRODUCTS: Product[]= [
   {
    name: "Nokoss fait maison2",
    description: "Nokoss fait maison3",
    sold_price : 7,
    regular_price: 15,
    imageUrl: ["/assets/images/products/nokoss1.jpg"],
  },
   {
    name: "Nokoss fait maison",
    description: "Nokoss fait maison",
    sold_price : 27,
    regular_price: 47,
    imageUrl: ["/assets/images/products/nokosss.png"],
  },
    {
    name: "Nokoss fait maison2",
    description: "Nokoss fait maison3",
    sold_price : 7,
    regular_price: 15,
    imageUrl: ["/assets/images/products/nokoss1.jpg"],
  },
   {
    name: "Nokoss fait maison",
    description: "Nokoss fait maison",
    sold_price : 27,
    regular_price: 47,
    imageUrl: ["/assets/images/products/nokosss.png"],
  },
    {
    name: "Nokoss fait maison2",
    description: "Nokoss fait maison3",
    sold_price : 7,
    regular_price: 15,
    imageUrl: ["/assets/images/products/nokoss1.jpg"],
  },
   {
    name: "Nokoss fait maison",
    description: "Nokoss fait maison",
    sold_price : 27,
    regular_price: 47,
    imageUrl: ["/assets/images/products/nokosss.png"],
  },
    {
    name: "Nokoss fait maison2",
    description: "Nokoss fait maison3",
    sold_price : 7,
    regular_price: 15,
    imageUrl: ["/assets/images/products/nokoss1.jpg"],
  },
   {
    name: "Nokoss fait maison",
    description: "Nokoss fait maison",
    sold_price : 27,
    regular_price: 47,
    imageUrl: ["/assets/images/products/nokosss.png"],
  },
    {
    name: "Nokoss fait maison2",
    description: "Nokoss fait maison3",
    sold_price : 7,
    regular_price: 15,
    imageUrl: ["/assets/images/products/nokoss1.jpg"],
  },
   {
    name: "Nokoss fait maison",
    description: "Nokoss fait maison",
    sold_price : 27,
    regular_price: 47,
    imageUrl: ["/assets/images/products/nokosss.png"],
  },
    {
    name: "Nokoss fait maison2",
    description: "Nokoss fait maison3",
    sold_price : 7,
    regular_price: 15,
    imageUrl: ["/assets/images/products/nokoss1.jpg"],
  }, {
    name: "Nokoss fait maison",
    description: "Nokoss fait maison",
    sold_price : 27,
    regular_price: 47,
    imageUrl: ["/assets/images/products/nokosss.png"],
  },
    {
    name: "Nokoss fait maison2",
    description: "Nokoss fait maison3",
    sold_price : 7,
    regular_price: 15,
    imageUrl: ["/assets/images/products/nokoss1.jpg"],
  }, {
    name: "Nokoss fait maison",
    description: "Nokoss fait maison",
    sold_price : 27,
    regular_price: 47,
    imageUrl: ["/assets/images/products/nokosss.png"],
  },
    {
    name: "Nokoss fait maison2",
    description: "Nokoss fait maison3",
    sold_price : 7,
    regular_price: 15,
    imageUrl: ["/assets/images/products/nokoss1.jpg"],
  },
  ]
